title: MobiController Docs
description: Die Dokumentation für den Mobi
theme: just-the-docs

url: https://fhwn-robotik.github.io/MobiController-Docs/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Zurück zum Anfang"

callouts:
  highlight:
    color: yellow
  
  note:
    title: Hinweis
    color: purple

  important:
    title: Wichtig
    color: blue

  warning:
    title: Achtung
    color: red