title: MobiController Docs
description: Die Dokumentation für den Mobi
theme: just-the-docs

url: https://flo2410.github.io/MobiController-Docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
